### ISSUE TITLE
[BUG] - Hitting the /api/1/posts endpoint without valid authorisation generates 500 internal error

### ISSUE THREAD

**Issue by JosiahBull** [se310-t6/politicry#33]
### Description

Hitting the api with invalid authorization credentials generates an error.

### Reproduction steps

```bash
1. Start API
2. Send POST `/api/1/posts` with basic auth attached, but invalid tokens
```

### Logs

```bash
politicry-api         | ERROR:src:ERROR: A fatal error occurred: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
politicry-api         | Traceback (most recent call last):
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
politicry-api         |     response = self.full_dispatch_request()
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
politicry-api         |     rv = self.handle_user_exception(e)
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1521, in full_dispatch_request
politicry-api         |     rv = self.preprocess_request()
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1861, in preprocess_request
politicry-api         |     rv = self.ensure_sync(before_func)()
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask_limiter/extension.py", line 987, in _check_request_limit
politicry-api         |     raise e
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask_limiter/extension.py", line 971, in _check_request_limit
politicry-api         |     self.__evaluate_limits(endpoint, all_limits)
politicry-api         |   File "/usr/local/lib/python3.10/site-packages/flask_limiter/extension.py", line 909, in __evaluate_limits
politicry-api         |     limit_key = lim.key_func()
politicry-api         |   File "/usr/src/app/src/__init__.py", line 76, in <lambda>
politicry-api         |     key_func=lambda: current_user.username,
politicry-api         | AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
```

**Comment by Zasheus** [comment]
lgtm

**Comment by lche262** [comment]
looks good to me!
